// <auto-generated />
using System;
using GerenciamentoAtivos.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GerenciamentoAtivos.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260707150128_EstruturaInicialFii")]
    partial class EstruturaInicialFii
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GerenciamentoAtivos.Domain.Models.Administradora", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CnpjEmpresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CnpjFundo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Administradora");
                });

            modelBuilder.Entity("GerenciamentoAtivos.Domain.Models.Ativo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("AdministradoraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoFii")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("PrecoCota")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantidadeCotas")
                        .HasColumnType("int");

                    b.Property<decimal>("RendimentoUnitario")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("SegmentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ValorPatrimonial")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AdministradoraId");

                    b.HasIndex("SegmentoId");

                    b.ToTable("Ativos");
                });

            modelBuilder.Entity("GerenciamentoAtivos.Domain.Models.Segmento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Segmentos");
                });

            modelBuilder.Entity("GerenciamentoAtivos.Domain.Models.Ativo", b =>
                {
                    b.HasOne("GerenciamentoAtivos.Domain.Models.Administradora", "Administradora")
                        .WithMany("Ativos")
                        .HasForeignKey("AdministradoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GerenciamentoAtivos.Domain.Models.Segmento", "Segmento")
                        .WithMany("Ativos")
                        .HasForeignKey("SegmentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administradora");

                    b.Navigation("Segmento");
                });

            modelBuilder.Entity("GerenciamentoAtivos.Domain.Models.Administradora", b =>
                {
                    b.Navigation("Ativos");
                });

            modelBuilder.Entity("GerenciamentoAtivos.Domain.Models.Segmento", b =>
                {
                    b.Navigation("Ativos");
                });
#pragma warning restore 612, 618
        }
    }
}
